const profanity_words = [
    "gay",
    "allah",
    "xylex",
    "cancer",
    "gay nigga",
    "nigger",
    "nigga",
    "discord.gg",
    "gay sex",
    "porn",
    "rape",
    "rapist",
    "https://",
    "n1gger",
    "n1gga",
    "nig nog",
    "nigaboo",
    "nigg3r",
    "nigg4h",
    "nigga",
    "niggah",
    "niggas",
    "niggaz",
    "nigger",
    "niggers",
    "niggle",
    "niglet",
    "nig-nog",
    "negro",
    "porno",
    "pornography",
    "pornos",
    "cancer mother",
    "whore mother",
    "cancer mom",
    "whore mom",
    "child porn",
    "child porno",
    "child pornography",
    "child rape",
]

export const isWordBanned = (word) => {
    const lowerCaseWord = word.toLowerCase();
    return profanity_words.some(profanity => lowerCaseWord.includes(` ${profanity} `) || lowerCaseWord.startsWith(`${profanity} `) || lowerCaseWord.endsWith(` ${profanity}`) || lowerCaseWord === profanity);
}
