export const pairnames = [
  {label: "XAUUSD", value: "xauusd"},
  {label: "NAS100", value: "nas100"},
  {label: "ETHUSD", value: "ethusd"},
  {label: "BTCUSD", value: "btcusd"},
  {label: "EURUSD", value: "eurusd"},
  {label: "GBPCHF", value: "gbpchf"},
  {label: "GBPUSD", value: "gbpusd"},
  {label: "USDJPY", value: "usdjpy"},
  {label: "AUDUSD", value: "audusd"},
  {label: "GBPJPY", value: "gbpjpy"},
  {label: "USDCAD", value: "usdcad"},
  {label: "USDCHF", value: "usdchf"},
  {label: "EURJPY", value: "eurjpy"},
  {label: "NZDUSD", value: "nzdusd"},
  {label: "EURGBP", value: "eurgbp"},
  {label: "GBPAUD", value: "gbpaud"},
  {label: "EURAUD", value: "euraud"},
  {label: "AUDCAD", value: "audcad"},
  {label: "CADJPY", value: "cadjpy"},
  {label: "GBPCAD", value: "gbpcad"},
  {label: "EURCAD", value: "eurcad"},
  {label: "AUDCHF", value: "audchf"},
  {label: "EURNZD", value: "eurnzd"},
  {label: "EURCHF", value: "eurchf"},
  {label: "GBPNZD", value: "gbpnzd"},
  {label: "CHFJPY", value: "chfjpy"},
  {label: "AUDNZD", value: "audnzd"},
  {label: "CADCHF", value: "cadchf"},
  {label: "NZDCAD", value: "nzdcad"},
  {label: "NZDCHF", value: "nzdchf"},
  {label: "NZDJPY", value: "nzdjpy"},
  {label: "AUDJPY", value: "audjpy"},
];

export const timeframes = [
  { id: "1M", label: "1 min" },
  { id: "3M", label: "3 min" },
  { id: "5M", label: "5 min" },
  { id: "15M", label: "15 min" },
  { id: "30M", label: "30 min" },
  { id: "H1", label: "1 hour" },
  { id: "H4", label: "4 hour" },
  { id: "1d", label: "1 day" }
];